workflows:
  quickbill-android:
    name: QuickBill Android APK Build
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.qb.quickbill"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
      - emu.imam.ei@gmail.com
      recipients:
      - emu.imam.ei@gmail.com
        notify:
          success: true
          failure: true